-- AlterTable
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "paymentStatus" TEXT NOT NULL DEFAULT 'PENDING';
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "bkashSenderNumber" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "bkashTrxId" TEXT;
